### ISSUE TITLE
업데이트 내용 및 수정 필요

### ISSUE THREAD

**Issue by khm1102** [Gaft-sdhs/no-gambling-front#2]
# update
- PWA 적용
- babel 사용하여 콘솔 제거 (개발 환경 및 빌드)

# 수정 요청
- [모바일] 메뉴 클릭 후 다른 곳을 터치했을 때 메뉴 닫기 @paulsea27115 
- [모바일] 튜토리얼 모달창 수정 @ghkdwlsgk

**Comment by paulsea27115** [comment]
[모바일] 메뉴 클릭 후 다른 곳을 터치했을 때 메뉴 닫기 
완료

**Comment by paulsea27115** [comment]
기간 마감(프로젝트 마감)으로 이슈 닫음
튜토리얼 모달창 수정 X
